language: node_js
node_js: stable

# 加快下次的访问速度
cache:
  directories:
    - node_modules

# 当名为hexo的分支有变化，就重新编译一次
branches:
  only:
    - hexo

before_install:
  - npm install -g hexo-cli
  

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save


# before_script:
# - npm install -g gulp
# 编译hexo  
script:
  - hexo clean
  - hexo generate

after_script:
#  - cd ./public
#  - git init
  - git config user.name "tinyplan"
  - git config user.email "3405443386@qq.com"
#  - git add .
#  - git commit -m "Update docs"
#  - git push --force --quiet "${Travis}@${GH_REF}" master:master
  - sed -i "s/Travis/${Travis}/g" ./_config.yml
  - hexo deploy

# 推送位置
deploy:
- type: git
  # 下方的gh_token会被.travis.yml中sed命令替换
  repo: https://Travis@github.com:tinyplan/tinyplan.github.io.git
  branch: master
