# 引用别名 theme
# 配置属性名时不要加'-',解析会有问题 (如xxx-xxx: xxx会解析失败)
# site name
prefixName: さくら荘その
siteName: tinyplan
# favicon and site master avatar
# 以下均为cdn地址
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
# url为点击站点标题后跳转的地址
url: https://tinyplan.github.io
# 站点介绍
description: 「 最是人间留不住 朱颜辞镜花辞树 」
cdn: https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0
pjax: 1
# 1开启
mathjax: 0

notice: 欢迎光临我的小站 ╰(*°▽°*)╯ 小站还在建设中哦！ヽ(*。>Д<)o゜
lazyloadImg: https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/loader/orange.progress-bar-stripe-loader.svg

# 默认的配置
default_authorName: tinyplan
default_authorAbout: 作者没有留下讯息哦！Σ( ° △ °|||)︴

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/tech/, fa: fa-code }, 
    生活: {path: /categories/live/, fa: fa-file-text-o }, 
    资源: {path: /categories/resource/, fa: fa-cloud-download }, 
    随想: {path: /categories/whimsy/, fa: fa-commenting-o },
    转载: {path: /categories/reprint/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/bookList/, fa: fa-th-list }, 
    番组: {path: /bangumi/, fa: fa-film }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  专栏: { path: /categories/tech/, fa: fa-code faa-shake, submenus: {
    Nginx: {path: /tags/nginx, fa: fa-html5},
    Linux: {path: /tags/linux, fa: fa-linux}
  } }
# 留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
# 赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: javascript:;, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura fa-spin},
    未来: {path: /future/, fa: fa-cog fa-spin},
  } }
# 客户端: { path: /client/, fa: fa-android faa-vertical }
# RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 轮播图 背景图片 更好的修改
# 图片格式转换 8
bg:
  - https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/cover/original/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/cover/original/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/cover/original/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/cover/original/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/cover/original/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/cover/original/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/cover/original/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/tinyplan/cdn@v2.0/img/cover/original/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/342927027, title: Bilibili, desc: 博主的b站空间, img: /img/startdash/bilibili.jpg}
  - {url: /, title: 园主的万事屋(未施工), desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 20/02/2019

#social  url, img PC端配置
#########
# 此处替换成自己的账户
#########
social:
  github: {url: http://github.com/tinyplan, img: /img/social/github.png}
  qq: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/qq.png}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  netease: {url: /#, img: /img/social/netease.png}
  zhihu: {url: /#, img: /img/social/zhihu.png}
  email: {url: /#, img: /img/social/email.svg}
  
#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/tinyplan, fa: fa-github, color: 333}
  weibo: {url: /#, fa: fa-weibo, color: dd4b39}
  qq: {url: /#, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
# 暂时不启用，具体位置在Sakura/layout/_partial/headertop.ejs中
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

# 左下角音乐播放器
# honjun 2660651585
aplayer: 
  id: 2434757581
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.5
  mutex: true

# Valine 评论系统
# 暂时关闭
valine: false
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ
